# generated by datamodel-codegen:
#   filename:  GenerationSource.json

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, constr


class SourceType(Enum):
    question = 'question'
    question_solution = 'question_solution'


class GenerationSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceType: SourceType
    sourceId: constr(min_length=1)
    modelCallIds: List[str]
    promptVersion: constr(min_length=1)
