# generated by datamodel-codegen:
#   filename:  ModelCall.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, confloat, conint, constr


class ModelCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    provider: constr(min_length=1)
    model: constr(min_length=1)
    taskType: constr(min_length=1)
    userId: Optional[str] = None
    lessonPacketId: Optional[str] = None
    inputTokens: Optional[conint(ge=0, le=9007199254740991)] = None
    outputTokens: Optional[conint(ge=0, le=9007199254740991)] = None
    estimatedCost: Optional[confloat(ge=0.0)] = None
    latencyMs: Optional[conint(ge=0, le=9007199254740991)] = None
    status: constr(min_length=1)
    errorMessage: Optional[str] = None
    createdAt: Optional[str] = None
    prepJobId: Optional[str] = None
    costBasis: Optional[constr(min_length=1)] = None
    promptVersion: Optional[str] = None
    requestHash: Optional[str] = None
