# generated by datamodel-codegen:
#   filename:  PrepGenerateRequest.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class PrepGenerateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1']
    tenantId: constr(min_length=1)
    jobId: constr(min_length=1)
    kpCode: constr(min_length=1)
