# generated by datamodel-codegen:
#   filename:  PrepJobRecord.json

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, conint, constr


class Status(Enum):
    pending = 'pending'
    running = 'running'
    validating = 'validating'
    done = 'done'
    failed = 'failed'


class PrepJobRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    status: Status
    kpCode: constr(min_length=1)
    promptVersion: constr(min_length=1)
    idempotencyKey: constr(min_length=1)
    attemptCount: conint(ge=0, le=9007199254740991)
    failureReason: Optional[str] = None
    lessonPacketId: Optional[str] = None
    createdAt: Optional[str] = None
    updatedAt: Optional[str] = None
