"""从 Zod 导出的 contracts/*.json 生成 Pydantic（D1 跨语言契约）。

TS 侧 `pnpm --filter @prep-forge/schemas contracts:gen` 由 Zod 写 JSON Schema；
本脚本锁定版本 datamodel-code-generator 生成对应 Pydantic（提交进仓）。
两侧 CI「重生成 + git diff --exit-code」守漂移。

用法：
  uv run python scripts/gen_contracts.py          # 重新生成
  uv run python scripts/gen_contracts.py --check   # 生成后 git diff，漂移则退出码 1

`--disable-timestamp` 保证同输入同字节，git diff 守卫才稳。
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# 契约文件名（无扩展） → 根类名（对齐 TS 导出名）。
CONTRACTS = [
    "ModelCall",
    "QualityGateResult",
    "PrepJobRecord",
    "GenerationSource",
    "PrepGenerateRequest",
    "PrepGenerateResult",
]

_AI_WORKER = Path(__file__).resolve().parents[1]
_REPO_ROOT = _AI_WORKER.parents[1]
_CONTRACTS_JSON = _REPO_ROOT / "packages" / "schemas" / "contracts"
_OUT_DIR = _AI_WORKER / "ai_worker" / "contracts"


def _snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def generate() -> None:
    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    for cls in CONTRACTS:
        src = _CONTRACTS_JSON / f"{cls}.json"
        if not src.exists():
            sys.exit(f"missing contract source: {src}")
        out = _OUT_DIR / f"{_snake(cls)}.py"
        subprocess.run(
            [
                "datamodel-codegen",
                "--input", str(src),
                "--input-file-type", "jsonschema",
                "--output-model-type", "pydantic_v2.BaseModel",
                "--class-name", cls,
                "--disable-timestamp",
                "--output", str(out),
            ],
            check=True,
        )
        print(f"wrote ai_worker/contracts/{out.name}")

    # 生成 __init__.py 重导出根类（也进 git diff 守卫，无手维护漂移）。
    lines = [
        "# generated by scripts/gen_contracts.py — do not edit.\n",
        "from __future__ import annotations\n",
        "\n",
    ]
    for cls in CONTRACTS:
        lines.append(f"from ai_worker.contracts.{_snake(cls)} import {cls} as {cls}\n")
    lines.append("\n")
    lines.append("__all__ = [\n")
    for cls in CONTRACTS:
        lines.append(f'    "{cls}",\n')
    lines.append("]\n")
    (_OUT_DIR / "__init__.py").write_text("".join(lines))
    print("wrote ai_worker/contracts/__init__.py")


def check() -> None:
    generate()
    result = subprocess.run(
        ["git", "diff", "--exit-code", "--", str(_OUT_DIR)],
        cwd=_REPO_ROOT,
    )
    if result.returncode != 0:
        sys.exit(
            "contract drift: regenerated Pydantic differs from committed copy. "
            "Run `uv run python scripts/gen_contracts.py` and commit."
        )


if __name__ == "__main__":
    check() if "--check" in sys.argv[1:] else generate()
